conda:
  environment: .rtd-environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

python:
   install:
     - requirements: docs/requirements.txt

sphinx:
   configuration: docs/conf.py


