
name: bagle 

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.11
    - astropy
    - numpydoc 
    - matplotlib
    - numpy
    - celerite
    - ephem
    - joblib
    - jplephem
    - graphviz 
    - pymultinest
    - dynesty
    - pytest
    - mpi4py
    - sphinx_rtd_theme
    - pip:
        - sphinxcontrib-video

